dispatcher.py:520 #INFO    [2024-03-02 13:35:34,401] - aiogram.dispatcher - Start polling
dispatcher.py:339 #INFO    [2024-03-02 13:35:34,588] - aiogram.dispatcher - Run polling for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:171 #INFO    [2024-03-02 13:35:49,752] - aiogram.event - Update id=555690102 is handled. Duration 413 ms by bot id=6251976390
dispatcher.py:451 #WARNING [2024-03-02 13:36:38,737] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:355 #INFO    [2024-03-02 13:36:38,739] - aiogram.dispatcher - Polling stopped for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:547 #INFO    [2024-03-02 13:36:38,740] - aiogram.dispatcher - Polling stopped
bot.py:28 #INFO    [2024-03-02 13:36:42,539] - __main__ - Starting bot
dispatcher.py:520 #INFO    [2024-03-02 13:36:43,084] - aiogram.dispatcher - Start polling
dispatcher.py:339 #INFO    [2024-03-02 13:36:43,161] - aiogram.dispatcher - Run polling for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:171 #INFO    [2024-03-02 13:36:54,985] - aiogram.event - Update id=555690103 is handled. Duration 462 ms by bot id=6251976390
dispatcher.py:451 #WARNING [2024-03-02 13:55:24,254] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:355 #INFO    [2024-03-02 13:55:24,254] - aiogram.dispatcher - Polling stopped for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:547 #INFO    [2024-03-02 13:55:24,255] - aiogram.dispatcher - Polling stopped
bot.py:18 #INFO    [2024-03-02 13:55:28,226] - __main__ - Starting bot
dispatcher.py:520 #INFO    [2024-03-02 13:55:29,445] - aiogram.dispatcher - Start polling
dispatcher.py:339 #INFO    [2024-03-02 13:55:29,531] - aiogram.dispatcher - Run polling for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:171 #INFO    [2024-03-02 13:55:43,480] - aiogram.event - Update id=555690104 is handled. Duration 452 ms by bot id=6251976390
dispatcher.py:171 #INFO    [2024-03-02 13:55:50,500] - aiogram.event - Update id=555690105 is handled. Duration 514 ms by bot id=6251976390
dispatcher.py:171 #INFO    [2024-03-02 13:56:00,886] - aiogram.event - Update id=555690106 is handled. Duration 666 ms by bot id=6251976390
dispatcher.py:218 #ERROR   [2024-03-03 11:06:45,415] - aiogram.dispatcher - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
dispatcher.py:220 #WARNING [2024-03-03 11:06:45,419] - aiogram.dispatcher - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6251976390)
dispatcher.py:232 #INFO    [2024-03-03 11:06:56,784] - aiogram.dispatcher - Connection established (tryings = 1, bot id = 6251976390)
dispatcher.py:451 #WARNING [2024-03-03 11:10:00,016] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:355 #INFO    [2024-03-03 11:10:00,040] - aiogram.dispatcher - Polling stopped for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:547 #INFO    [2024-03-03 11:10:00,042] - aiogram.dispatcher - Polling stopped
bot.py:16 #INFO    [2024-03-14 18:06:59,027] - __main__ - Starting bot
dispatcher.py:520 #INFO    [2024-03-14 18:07:05,132] - aiogram.dispatcher - Start polling
dispatcher.py:339 #INFO    [2024-03-14 18:07:05,266] - aiogram.dispatcher - Run polling for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:171 #INFO    [2024-03-14 18:07:07,564] - aiogram.event - Update id=555690661 is handled. Duration 331 ms by bot id=6251976390
dispatcher.py:171 #INFO    [2024-03-14 18:07:29,460] - aiogram.event - Update id=555690662 is not handled. Duration 1055 ms by bot id=6251976390
dispatcher.py:313 #ERROR   [2024-03-14 18:07:29,461] - aiogram.event - Cause exception while process update id=555690662 by bot id=6251976390
TelegramBadRequest: Telegram server says - Bad Request: message is too long
Traceback (most recent call last):
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 307, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 274, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/daniil/Work/PycharmProjects/TelegramBots/Work_Project/handlers/user_handlers.py", line 1325, in process_english_dict_command
    mes_del_3 = await message.answer(text=new_text)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/methods/base.py", line 82, in emit
    return await bot(self)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/bot.py", line 433, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/session/base.py", line 251, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 170, in make_request
    response = self.check_response(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/session/base.py", line 114, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message is too long
dispatcher.py:451 #WARNING [2024-03-14 18:09:06,833] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:355 #INFO    [2024-03-14 18:09:06,834] - aiogram.dispatcher - Polling stopped for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:547 #INFO    [2024-03-14 18:09:06,835] - aiogram.dispatcher - Polling stopped
bot.py:16 #INFO    [2024-03-14 18:09:11,026] - __main__ - Starting bot
dispatcher.py:520 #INFO    [2024-03-14 18:09:11,580] - aiogram.dispatcher - Start polling
dispatcher.py:339 #INFO    [2024-03-14 18:09:11,729] - aiogram.dispatcher - Run polling for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:171 #INFO    [2024-03-14 18:09:15,047] - aiogram.event - Update id=555690664 is handled. Duration 484 ms by bot id=6251976390
dispatcher.py:171 #INFO    [2024-03-14 18:09:17,715] - aiogram.event - Update id=555690665 is not handled. Duration 562 ms by bot id=6251976390
dispatcher.py:313 #ERROR   [2024-03-14 18:09:17,716] - aiogram.event - Cause exception while process update id=555690665 by bot id=6251976390
TelegramBadRequest: Telegram server says - Bad Request: message is too long
Traceback (most recent call last):
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 307, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 274, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/daniil/Work/PycharmProjects/TelegramBots/Work_Project/handlers/user_handlers.py", line 1325, in process_english_dict_command
    mes_del_3 = await message.answer(text=new_text)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/methods/base.py", line 82, in emit
    return await bot(self)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/bot.py", line 433, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/session/base.py", line 251, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 170, in make_request
    response = self.check_response(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/session/base.py", line 114, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message is too long
dispatcher.py:451 #WARNING [2024-03-14 18:10:16,130] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:355 #INFO    [2024-03-14 18:10:16,131] - aiogram.dispatcher - Polling stopped for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:547 #INFO    [2024-03-14 18:10:16,132] - aiogram.dispatcher - Polling stopped
bot.py:16 #INFO    [2024-03-14 18:10:20,207] - __main__ - Starting bot
dispatcher.py:520 #INFO    [2024-03-14 18:10:21,765] - aiogram.dispatcher - Start polling
dispatcher.py:339 #INFO    [2024-03-14 18:10:22,085] - aiogram.dispatcher - Run polling for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:171 #INFO    [2024-03-14 18:10:24,993] - aiogram.event - Update id=555690667 is handled. Duration 329 ms by bot id=6251976390
dispatcher.py:171 #INFO    [2024-03-14 18:10:27,434] - aiogram.event - Update id=555690668 is not handled. Duration 546 ms by bot id=6251976390
dispatcher.py:313 #ERROR   [2024-03-14 18:10:27,435] - aiogram.event - Cause exception while process update id=555690668 by bot id=6251976390
TelegramBadRequest: Telegram server says - Bad Request: message is too long
Traceback (most recent call last):
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 307, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 274, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/daniil/Work/PycharmProjects/TelegramBots/Work_Project/handlers/user_handlers.py", line 1325, in process_english_dict_command
    mes_del_3 = await message.answer(text=new_text)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/methods/base.py", line 82, in emit
    return await bot(self)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/bot.py", line 433, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/session/base.py", line 251, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 170, in make_request
    response = self.check_response(
  File "/home/daniil/.local/lib/python3.10/site-packages/aiogram/client/session/base.py", line 114, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message is too long
dispatcher.py:451 #WARNING [2024-03-14 18:21:06,321] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:355 #INFO    [2024-03-14 18:21:06,322] - aiogram.dispatcher - Polling stopped for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:547 #INFO    [2024-03-14 18:21:06,322] - aiogram.dispatcher - Polling stopped
bot.py:16 #INFO    [2024-03-14 18:21:10,144] - __main__ - Starting bot
dispatcher.py:520 #INFO    [2024-03-14 18:21:10,667] - aiogram.dispatcher - Start polling
dispatcher.py:339 #INFO    [2024-03-14 18:21:10,778] - aiogram.dispatcher - Run polling for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:451 #WARNING [2024-03-14 18:23:01,662] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:355 #INFO    [2024-03-14 18:23:01,663] - aiogram.dispatcher - Polling stopped for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:547 #INFO    [2024-03-14 18:23:01,664] - aiogram.dispatcher - Polling stopped
bot.py:16 #INFO    [2024-03-14 18:23:05,643] - __main__ - Starting bot
dispatcher.py:520 #INFO    [2024-03-14 18:23:06,275] - aiogram.dispatcher - Start polling
dispatcher.py:339 #INFO    [2024-03-14 18:23:06,345] - aiogram.dispatcher - Run polling for bot @MyMoulagaBot id=6251976390 - 'Working Field'
dispatcher.py:171 #INFO    [2024-03-14 18:23:07,137] - aiogram.event - Update id=555690669 is handled. Duration 285 ms by bot id=6251976390
